### ISSUE TITLE
解压缩出错

### ISSUE THREAD

**Issue by WANGFANG345799-star** [Tokeii0/LovelyMem#14]
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\MemProcFS\python\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\MemProcFS\python\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\MemProcFS\python\Lib\site-packages\setuptools\cli-arm64.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\MemProcFS\python\Lib\site-packages\setuptools\gui-arm64.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\python3\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\python3\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\python3\Lib\site-packages\setuptools\cli-arm64.exe
! C:\Users\ADMIN\Desktop\Lovelymemv0.8.7z: 未知方式于 Tools\python3\Lib\site-packages\setuptools\gui-arm64.exe

**Comment by Tokeii0** [comment]
无影响
