### ISSUE TITLE
加载netstat时，显示结果中DstAddr和DstPort结果不正确

### ISSUE THREAD

**Issue by Gre3nStars** [Tokeii0/LovelyMem#8]
![image](https://github.com/Tokeii0/LovelyMem/assets/12098899/85a2136c-91fa-4ff2-a6d9-2ace8cbc7fea)
执行加载netstat时，加载的结果中DstAddr和DstPort显示不正确，加载的netstat-v.txt中原文本文件也都是*号，是不是MemProcFS处理得到的这个结果本身就有问题，而通过vol执行结果是有的
![image](https://github.com/Tokeii0/LovelyMem/assets/12098899/5a7d14f8-3db9-46d2-a758-b5fc1139ea2d)

**Comment by Tokeii0** [comment]
MemprocFS对一些老版本镜像不兼容，参考https://github.com/ufrisk/MemProcFS/issues/283
